target:
- label
continuous_cols:
- url_length
- num_dots
- has_https
- has_ip
- num_subdirs
- num_params
- suspicious_words
- special_char_count
- digits_count
- entropy
categorical_cols:
- tld
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 2
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true
dataloader_kwargs: {}
task: classification
head: LinearHead
head_config:
  layers: ''
embedding_dims: null
embedding_dropout: 0.0
batch_norm_continuous_input: true
learning_rate: 0.001
loss: CrossEntropyLoss
metrics:
- accuracy
metrics_prob_input:
- false
metrics_params:
- {}
target_range: null
virtual_batch_size: 128
seed: 42
_module_src: models.tabnet
_model_name: TabNetModel
_backbone_name: Backbone
_config_name: TabNetModelConfig
n_d: 16
n_a: 16
n_steps: 3
gamma: 1.3
n_independent: 2
n_shared: 2
mask_type: sparsemax
grouped_features: null
batch_size: 32
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 20
min_epochs: 1
max_time: null
accelerator: cpu
devices: -1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: valid_loss
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 5
early_stopping_kwargs: {}
checkpoints: valid_loss
checkpoints_path: saved_models
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
checkpoints_kwargs: {}
load_best: true
track_grad_norm: -1
progress_bar: rich
precision: 32
trainer_kwargs: {}
optimizer: Adam
optimizer_params: {}
lr_scheduler: null
lr_scheduler_params: {}
lr_scheduler_monitor_metric: valid_loss
categorical_dim: 1
enable_checkpointing: true
